### ISSUE TITLE
considerations from the polykey app

### ISSUE THREAD

**Issue by robert-cronin** [MatrixAI/Typescript-Demo-Spa#1]
This is an issue to discuss some considerations from Polykey that can be applicable to the SPA demo. Including vuejs configuration, vuex setup, webpack, JSX in Vue templates, babel.

**Comment by robert-cronin** [comment]
Most of the stuff relevant to SPA is in the [renderer folder](https://github.com/MatrixAI/PolyKey/tree/mvp/src/renderer). There is still a lot to clean up and this repo should probably drive Polykey in the future.

**VueJS Configuration**
I've used the [create vue project command](https://cli.vuejs.org/guide/creating-a-project.html) with Babel, TypeScript, Router, Vuex, Linter (ESLint) and Unit Testing (Jest) selected for the Polykey app. 

I am also using single file components (.vue files) as opposed to separating JS/HTML/CSS.

**Typescript**
To get typing in vue components, you need to add the `lang="ts"` flag to the script tags.

**StoryBook**
For adding story book there is the [storybook plugin](https://github.com/storybookjs/vue-cli-plugin-storybook). You can add it with `vue add storybook`. I suggest suggest component story format and StoryDocs.

**Vuex Setup**
I am using a module called [vuex-module-decorators](https://github.com/championswimmer/vuex-module-decorators) to make the process little simpler. It creates the getters/setters/methods etc all behind the scenes. I have split up my models into the various domains of Polykey (Keys/Vaults/Peers etc) just to keep in line with good domain modelling. (e.g. the [keys](https://github.com/MatrixAI/PolyKey/blob/mvp/src/renderer/store/modules/Keys.ts) model). Then you can bring them in

In the vue components, you can [vuex-class](https://github.com/ktsn/vuex-class) to access the namespaces/domain models in the store. There is a good example of this in the [keys](https://github.com/MatrixAI/PolyKey/blob/mvp/src/renderer/components/keys/Keys.vue) component.

Polykey App still has a long way to go but hopefully that helps :grin:

**Comment by CMCDragonkai** [comment]
Fixed due to #3.

We will deal with vuex separately.

The storybook stuff still doesn't support Vue 3 yet, so we will wait for that soon.

The Polykey GUI should be based on this repo's master as well, of course it will need to be adapted for Electron frontend. We will have the nativescript run concurrently off the same repo I believe, except where we can keep the branding and art assets owned by Matrix AI:

* https://opensource.stackexchange.com/questions/500/does-being-open-sourced-mean-others-can-use-my-logo?rq=1
* https://opensource.stackexchange.com/questions/2224/how-should-i-license-my-projects-logo
